### ISSUE TITLE
Add width attribute to mdc-select

### ISSUE THREAD

**Issue by djensen47** [Ullfis/aurelia-mdc-bridge#22]
It looks like the mdc-select component's width is auto calculated. It might be nice to be able to manually specify a width. This could help avoid it being too long and getting clipped or appearing too short next to other form fields.

**Comment by djensen47** [comment]
BTW, I'm here to help work on these things. I've switched from a mix of materialize-bridge and mdc-bridge to 100% mdc-bridge. So I'm in active development finding issues along the way.

**Comment by Ullfis** [comment]
Much sorry for the inactivity lately. I have been moving and Internet is still not operational + tons of work..

Your work is awesome! Thank you very much for helping :+1: I will read up on whats new in mdc version 0.21 – 0.23 and scratch my head before merging changes. Plz be patient.

**Comment by Ullfis** [comment]
Try this:

css:

```css
.my-cont .mdc-select {
  min-width: 250px;
}
.my-cont .mdc-select .mdc-list-item {
  min-width: 250px;
}
```

```html
<mdc-select class="my-cont" ...
```
